[package]
name = "temporary_basic_example"
version = "0.1.0"
authors = ["Sage Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
autotests = false
autobenches = false
edition = "2021"
publish = false


[dependencies]
diesel = { path = "../diesel/", features = ["postgres"] }
